SELECT TITLE,	A.BOARD_ID,	A.REPLY_ID,	A.WRITER_ID,	A.CONTENTS,	DATE_FORMAT(A.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE FROM USED_GOODS_REPLY A JOIN USED_GOODS_BOARD B ON A.BOARD_ID = B.BOARD_ID
WHERE B.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY A.CREATED_DATE, TITLE
