SELECT 
TITLE,
a.BOARD_ID,
b.REPLY_ID,
b.WRITER_ID,
b.CONTENTS,
DATE_FORMAT(b.CREATED_DATE, "%Y-%m-%d") CREATED_DATE
from
USED_GOODS_BOARD a
join
USED_GOODS_REPLY b
on
a.BOARD_ID = b.BOARD_ID
where
1=1
and DATE_FORMAT(a.CREATED_DATE, "%Y-%m") = "2022-10"
order by
b.CREATED_DATE,
TITLE